from strategy.drive_at_ball import DriveAtBall
from strategy.drive_at_center import DriveAtCenter
from strategy.drive_behind_ball import DriveBehindBall
from strategy.drive_at_my_goal import DriveAtMyGoal
